server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
    gateway:
      routes:
      - id: host_route
        uri: lb://servicea
        predicates:
          - Path=/a/**
  zipkin:
    locator:
      discovery:
        enabled: true
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1.0