server:
  port: 8005
mybatis:
  mapperLocations: classpath*:com/tys/**/dap/*Mapper.xml
spring:
  application:
    name: shardingdemo
#  datasource:
#    url: jdbc:mysql://39.106.214.109:3306/demo0
#    username: icoding
#    password: icoding
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
  shardingsphere:
    datasource:
      names: demo0
      demo0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://39.106.214.109:3306/demo0
        username: icoding
        password: icoding
    sharding:
      tables:
        userorder:
          actual-data-nodes: demo$->{0..1}.userorder$->{0..1}
          table-strategy:
            inline:
              sharding-column: month
              algorithm-expression: userorder$->{month % 12}
          database-strategy:
            inline:
              sharding-column: month
              algorithm-expression: demo$->{month % 2}
          key-generator:
            column: id
            type: SNOWFLAKE