server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
    gateway:
      routes:
      - id: host_route
        uri: lb://servicea
        predicates:
          - Path=/a/**